### ISSUE TITLE
Word/phrase alternation in allowed translations

### ISSUE THREAD

**Issue by Sobsz** [kantord/LibreLingo#1460] opened 2021-07-20 18:47 UTC
Words can often have multiple translations, such as when the target language has distinctions that the source language doesn't (e.g. grammatical gender). Each such word doubles the amount of needed alternatives. As an example, the English sentence `Did you do it?` can be translated to at least these 8 Polish sentences:

> Czy ty to zrobiłaś?
> Czy ty to zrobiłeś?
> Czy to zrobiłaś?
> Czy to zrobiłeś?
> Zrobiłaś to?
> Zrobiłeś to?
> Zrobiłaś?
> Zrobiłeś?

(3 of these are output by Google Translate, 1 is a plausible version of the first, and the remaining 4 have the gender switched.)

This can be a pain to edit and check the correctness of, especially with longer sentences. A simple alternation scheme inspired by [spintax](https://spintaxtool.appspot.com/) could bring the example down to just 2 entries:

> Czy {ty|} to zrobił{a|e}ś?
> Zrobił{a|e}ś {to|}?

It is my understanding that whitespace is ignored when checking translations. However, for display purposes, it may be necessary to use this slightly less readable form:

> Czy{ ty|} to zrobił{a|e}ś?
> Zrobił{a|e}ś{ to|}?

If used in the main translation, the first option in each group could be displayed.

An optional quality-of-life feature would be to treat `{text}` the same as `{text|}`, but this is not necessary.

**Comment by kantord** [comment] 2021-07-20 19:37
thanks @Sobsz.

looks like this is a duplicate of https://github.com/kantord/LibreLingo/issues/1122

**Closed by kantord** 2021-07-20 19:37 UTC
