### ISSUE TITLE
Shorter courses

### ISSUE THREAD

**Issue by kivutar** [kantord/LibreLingo#619] opened 2020-08-16 04:34 UTC
**Is your feature request related to a problem? Please describe.**

The example spanish course exercice session takes too long. A series of exercices shouldn't take more than 4min to complete. I think it should contain 5 to 10 questions, not 30.

**Describe the solution you'd like**

Break each skill in sublevels: Animals lvl 1, Animals lvl 2, Animals lvl3..

**Comment by kantord** [comment] 2020-08-24 21:13
This is actually a duplicate of this: https://github.com/kantord/LibreLingo/issues/413

I just set a very uninformative title for that issue, so it was difficult to find :smiley_cat: 

I'll change the title there

**Closed by kantord** 2020-08-24 21:13 UTC
Labels: feature_request

**Comment by kantord** [comment] 2020-09-06 10:26
This should be fixed now BTW!
