### ISSUE TITLE
Teaching pronounciation

### ISSUE THREAD

**Issue by AndreVallestero** [kantord/LibreLingo#591] opened 2020-08-05 14:03 UTC
I feel like teaching pronunciation before beginning with words is very important, otherwise, people might begin with incorrect pronunciation and eventually learn it that way as it becomes habit. This is how DuoLingo teaches it's more foreign courses (Korean) and I think it's very effective. [StudySpanish](https://studyspanish.com/pronunciation) also does a great job of this and I hope something similar can be integrated within LibreLingo.

**Comment by kantord** [comment] 2020-08-06 05:34
Closing as duplicate of https://github.com/kantord/LibreLingo/issues/251

Thanks for reporting anyway, and if you have some more notes to add/alternative suggestion than what is laid out there, feel free to add it there :pray:

**Closed by kantord** 2020-08-06 05:34 UTC
Labels: feature_request
